kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "stream-image-patterns" 
  namespace: stream-image-patterns
spec:
  output:
    to:
      kind: DockerImage
      name: 'quay.io/fdavalo/stream-image-patterns:v1'
    pushSecret:
      name: fdavalo-fdavalo-robot-pull-secret
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.8'
  source:
    type: Git
    git:
      uri: 'https://github.com/fdavalo/stream-image-patterns'
  runPolicy: Serial
